
[window]
decorations = "buttonless"
startup_mode = "Maximized"
dynamic_padding = true
opacity = 0.92
padding = { x = 4, y = 2 }

[font]
size = 16

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.offset]
x = 0
y = 1

[font.glyph_offset]
x = 0
y = 0

[colors.primary]
background = "#0d1b0d"      # Dark green background
foreground = "#cce8cc"      # Light greenish text

[colors.normal]
black   = "#0d1b0d"
red     = "#a84c4c"
green   = "#6fb26f"
yellow  = "#c4b96f"
blue    = "#4f7fb2"
magenta = "#8f6fb2"
cyan    = "#6fb2a8"
white   = "#cce8cc"

[colors.bright]
black   = "#264d26"
red     = "#d97373"
green   = "#93d193"
yellow  = "#e3d98c"
blue    = "#6fa3d9"
magenta = "#b38fd9"
cyan    = "#8fd9d3"
white   = "#e8f3e8"

[colors.cursor]
text = "#0d1b0d"          # Cursor text
cursor = "#00ff66"        # Bright green cursor

[scrolling]
history = 10000
multiplier = 3

[cursor]
style = { shape = "Beam", blinking = "On" }
blink_interval = 500

[keyboard]
bindings = [
  { key = "N", mods = "Command", action = "None" },
  { key = "W", mods = "Command", action = "None" },
  { key = "Left",  mods = "Alt", chars = "\u001bb" },
  { key = "Right", mods = "Alt", chars = "\u001bf" },
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" }
]

[general]
live_config_reload = true

