[[language]]
name = "go"
auto-format = true
formatter = { command = "gofumpt" }

language-servers = [ "gopls" ]

[[language]]
name = "typescript"
auto-format = true

language-servers = [ "typescript-language-server" ]

[[language]]
name = "rust"
auto-format = true

language-servers = [ "rust-analyzer" ]
