inherits = "tokyonight"

# ============================================================================
# UI
# ============================================================================

"ui.background" = {}

"ui.cursorline" = { bg = "black" }
"ui.selection" = { bg = "gray" }

"ui.linenr" = { fg = "gray" }
"ui.linenr.selected" = { fg = "white", modifiers = ["bold"] }

# ============================================================================
# STATUSLINE
# ============================================================================

"ui.statusline" = { fg = "white", bg = "black" }
"ui.statusline.inactive" = { fg = "gray", bg = "black" }

# ============================================================================
# CURSORS
# ============================================================================

"ui.cursor" = { modifiers = ["reversed"] }

# ============================================================================
# DIAGNOSTICS
# ============================================================================

"warning" = { fg = "yellow" }
"error" = { fg = "red" }
"info" = { fg = "cyan" }
"hint" = { fg = "gray" }

# ============================================================================
# SYNTAX
# ============================================================================

"comment" = { fg = "gray", modifiers = ["italic"] }
"keyword" = { fg = "magenta" }
"string" = { fg = "green" }
"function" = { fg = "blue" }
"type" = { fg = "cyan" }
